# Generated by Django 2.1.11 on 2020-05-21 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsed_data',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
