# Generated by Django 2.1.11 on 2020-05-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20200521_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsed_data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
