# Generated by Django 2.1.11 on 2020-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_auto_20200521_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_data',
            name='size2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
