# Generated by Django 2.1.11 on 2020-05-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_auto_20200521_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsed_data',
            name='dateasd',
        ),
        migrations.AlterField(
            model_name='parsed_data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
