# Generated by Django 2.1.11 on 2020-05-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0007_auto_20200521_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsed_data',
            name='size2',
        ),
        migrations.AddField(
            model_name='parsed_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsed_data',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
