# Generated by Django 2.1.11 on 2020-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_auto_20200521_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(default='')),
                ('shop_id', models.CharField(blank=True, default='', max_length=50)),
                ('shop_password', models.CharField(blank=True, default='', max_length=50)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
