# Generated by Django 2.1.11 on 2020-05-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0009_shop2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop2',
            new_name='Other',
        ),
    ]
