# Generated by Django 2.1.11 on 2020-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0010_auto_20200529_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='other_chk',
            field=models.BooleanField(default=False),
        ),
    ]
