# Generated by Django 2.1.11 on 2020-06-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0011_shop_other_chk'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_data',
            name='basicInfo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parsed_data',
            name='storeName',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='parsed_data',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
