# Generated by Django 2.1.11 on 2020-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0012_auto_20200601_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsed_data',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
