# Generated by Django 2.1.11 on 2020-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0014_auto_20200604_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_data',
            name='img_folder_path',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
