# Generated by Django 2.1.11 on 2020-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0015_img_data_img_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_data',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
