# Generated by Django 3.2.3 on 2021-06-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0016_parsed_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_data',
            name='model_botton',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
